
email: erfansoheil.umz@gmail.com
description: >- # This adds a professional bio snippet to your footer
  ML Scientist / AI Engineer 
theme: minima

header_pages:
  - about.md
  - projects.md
  - research-notes.md
  - reading-notes.md
  - cv.md

