title: Erfan Soheil
email: erfansoheil.umz@gmail.com
description: >-
  AI Research Engineer | PhD in Mathematics
theme: minima

header_pages:
  - cv.md
  - about.md
  - projects.md
  - research-notes.md
  - writing-notes.md
  
